### ISSUE TITLE
should save state after each run on tests

### ISSUE THREAD

**Issue by deeperx** [rstacruz/mocha-jsdom#8]
Current implementation lets the manipulated document get used by the other tests. How to fix this?

````javascript
var jsdom = require('mocha-jsdom');
var expect = require('chai').expect;

describe('mocha tests', function () {

  jsdom();

  it('has a document', function () {
    var div = document.createElement('div');

    // MANIPULATE THE DOCUMENT
    div.id = 'aDiv';
    document.body.appendChild(div);

    expect(div.nodeName).eql('DIV');
  });

  // THIS WILL FAIL
  it('should not have the div from the above test', function () {
    expect(document.getElementById('aDiv')).to.not.exist;
  });

});
````

**Comment by rstacruz** [comment]
this is by design. the rationale for this is that when mocha is used in the browser, it acts the same way -- there's no way to reset the browser dom. this allows you to make tests that can run in io.js (via jsdom) and tests that can run in the browser.

to get around this, you can either...

- create an `afterEach()` hook to clean up things it makes (in this example, remove the `div` created), or
- put each example in a describe() context.

```js
describe('tests', function () {
  describe('test 1', function () {
    jsdom()
    it('does something', function() { ... })
  })
  describe('test 2', function () {
    jsdom()
    it('does something', function() { ... })
  })
})
```

**Comment by deeperx** [comment]
@rstacruz Reasonable, got it, thanks.
